### ISSUE TITLE
404 returned for artist bio info request.

### ISSUE THREAD

**Issue by nicfit** [redshodan/unsonic#10]
Click on artist in the library and dsub makes a request for artist bio info and shows an error dialog
"resource not found".  The request:

unsonic.nicfit.net    | 2017-03-28 01:31:17,388 INFO  [wsgi][waitress] 192.168.1.114 - - [28/Mar/2017:01:31:17 +0000] "GET /rest/getArtistInfo2.view?u=nicfit&s=XXXXXXXXXXXXX&t=XXXXXXXXXXXXXX&v=1.2.0&c=DSub&id=ar-9&includeNotPresent=true HTTP/1.1" 404 77 "-" "DSub"

**Comment by redshodan** [comment]
Haven't implemented that call yet. Check the TODO for the full list. It needs last.fm lookup of artist. I was planning on doing that a bit later.

**Comment by nicfit** [comment]
Thinking returning empty content or TODO, even, would make using dsub better till then. I might look at it.

**Comment by redshodan** [comment]
If you do look, check getArtistInfo. I already stubbed that one out for dsub.
