### ISSUE TITLE
Scrobble

### ISSUE THREAD

**Issue by nicfit** [redshodan/unsonic#2]
- [ ] Watch for stupid clients pushing the same scrobble multiple times too fast.

**Comment by redshodan** [comment]
Scrobbling locally to the database is currently done. Scrobbling to last.fm or the like will happen a bit later after the initial release settles down. Thanks for the enhancement request.

**Comment by nicfit** [comment]
See PR https://github.com/redshodan/unsonic/pull/5

**Comment by redshodan** [comment]
@nicfit: We've had a few changes to the scrobbling stuff. Is there anything left that you feel needs to be done for scrobbling?

**Comment by nicfit** [comment]
Don't think so. A related issue,  I did commit acb89796fa5a2faf68459cef11f6b547f3ec0d53
